imports:
    - { resource: parameters.yml }
    - { resource: security.yml }


framework:
    #esi:             ~
    translator: { fallback: "en" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "en"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true


# Monolog
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped_main
        # Groups
        grouped_main:
            type: group
            members: [streamed_main]
        # Streams
        streamed_main:
            type: stream
            path: %kernel.logs_dir%/%kernel.environment%.log
            level: error


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: ssl
    auth_mode: login
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"

# CIA
danaketh_ci:
    services:
        bitbucket: danaketh\CIBundle\Model\Bitbucket
        github: danaketh\CIBundle\Model\GitHub
        local: danaketh\CIBundle\Model\Local
        remote: danaketh\CIBundle\Model\Remote
    plugins:
        phpunit:
            class: danaketh\CIBundle\Plugin\PHPUnit
            name: "PHPUnit"
        phpcs:
            class: danaketh\CIBundle\Plugin\PHPCodeSniffer
            name: "PHP Code Sniffer"
        phpcpd:
            class: danaketh\CIBundle\Plugin\PHPCopyPasteDetector
            name: "PHP Copy & Paste Detector"
        phploc:
            class: danaketh\CIBundle\Plugin\PHPLoC
            name: "PHP LoC"
        phpmd:
            class: danaketh\CIBundle\Plugin\PHPMessDetector
            name: "PHP Mess Detector"
        pdepend:
            class: danaketh\CIBundle\Plugin\PDepend
            name: "PDepend"
        lint:
            class: danaketh\CIBundle\Plugin\Lint
            name: "Lint"
        codeception:
            class: danaketh\CIBundle\Plugin\Codeception
            name: "Codeception"
        phpspec:
            class: danaketh\CIBundle\Plugin\PHPSpec
            name: "PHPSpec"
        behat:
            class: danaketh\CIBundle\Plugin\Behat
            name: "Behat"
        composer:
            class: danaketh\CIBundle\Plugin\Composer
            name: "Composer"
    env:
        5_3_10: /usr/bin/php
        5_5_10: /opt/php-5.5.10/bin/php
        5_5_12: /opt/php-5.5.12/bin/php
